// <auto-generated />
using System;
using System.Collections.Generic;
using EfcDmPersistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EfcDmPersistence.Migrations
{
    [DbContext(typeof(DmContext))]
    [Migration("20251203073011_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("ViaEventAssociation.Core.Domain.Aggregates.Events.VeaEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("LocationMaxCapacity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Visibility")
                        .HasColumnType("INTEGER");

                    b.ComplexProperty<Dictionary<string, object>>("MaxGuestsNo", "ViaEventAssociation.Core.Domain.Aggregates.Events.VeaEvent.MaxGuestsNo#MaxGuests", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Value")
                                .HasColumnType("INTEGER");
                        });

                    b.HasKey("Id");

                    b.ToTable("VeaEvents", (string)null);
                });

            modelBuilder.Entity("ViaEventAssociation.Core.Domain.Aggregates.Guests.Guest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfilePictureUrlAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Guests", (string)null);
                });

            modelBuilder.Entity("ViaEventAssociation.Core.Domain.Aggregates.Events.VeaEvent", b =>
                {
                    b.OwnsMany("ViaEventAssociation.Core.Domain.Aggregates.Events.Entities.Invitation", "Invitations", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT")
                                .HasColumnName("InvitationId");

                            b1.Property<Guid>("EventId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("GuestId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Status")
                                .HasColumnType("INTEGER");

                            b1.HasKey("Id");

                            b1.HasIndex("EventId", "GuestId")
                                .IsUnique();

                            b1.ToTable("Invitations", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("EventId");
                        });

                    b.OwnsMany("ViaEventAssociation.Core.Domain.Aggregates.Guests.GuestId", "GuestList", b1 =>
                        {
                            b1.Property<Guid>("EventId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("Value")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT")
                                .HasColumnName("GuestId");

                            b1.HasKey("EventId", "Value");

                            b1.ToTable("EventParticipants", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("EventId");
                        });

                    b.OwnsOne("ViaEventAssociation.Core.Domain.Aggregates.Events.EventDescription", "Description", b1 =>
                        {
                            b1.Property<Guid>("VeaEventId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(250)
                                .HasColumnType("TEXT");

                            b1.HasKey("VeaEventId");

                            b1.ToTable("VeaEvents");

                            b1.WithOwner()
                                .HasForeignKey("VeaEventId");
                        });

                    b.OwnsOne("ViaEventAssociation.Core.Domain.Aggregates.Events.EventTimeRange", "TimeRange", b1 =>
                        {
                            b1.Property<Guid>("VeaEventId")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("EndTime")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("StartTime")
                                .HasColumnType("TEXT");

                            b1.HasKey("VeaEventId");

                            b1.ToTable("VeaEvents");

                            b1.WithOwner()
                                .HasForeignKey("VeaEventId");
                        });

                    b.OwnsOne("ViaEventAssociation.Core.Domain.Aggregates.Events.EventTitle", "Title", b1 =>
                        {
                            b1.Property<Guid>("VeaEventId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(75)
                                .HasColumnType("TEXT");

                            b1.HasKey("VeaEventId");

                            b1.ToTable("VeaEvents");

                            b1.WithOwner()
                                .HasForeignKey("VeaEventId");
                        });

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("GuestList");

                    b.Navigation("Invitations");

                    b.Navigation("TimeRange");

                    b.Navigation("Title")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
